name: Spring Boot Deploy Action
description: Composite action to deploy Spring Boot application
inputs:
  deploy-env:
    required: true
    description: The deployment environment

runs:
  using: "composite"
  steps:
    - name: Set execution permissions for deploy.sh
      run: chmod +x ${{ github.action_path }}/deploy.sh
      shell: bash

    - name: Run deployment script
      run: ${{ github.action_path }}/deploy.sh ${{ inputs.deploy-env }}
      shell: bash

